# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=30)),
                ('punto_partida', models.CharField(max_length=30)),
                ('fecha_partida', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ruta', models.CharField(max_length=30)),
                ('distancia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=50)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('grupos', models.ManyToManyField(default=None, related_name='usuarios', to='biker.Grupo')),
            ],
        ),
        migrations.AddField(
            model_name='ruta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biker.Usuario'),
        ),
        migrations.AddField(
            model_name='evento',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biker.Grupo'),
        ),
        migrations.AddField(
            model_name='evento',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biker.Ruta'),
        ),
    ]
