# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_partida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
